version: "3.8"

services:
  database:
    container_name: blog_db
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=blog
    ports:
      - 4444:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db: